apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-rest-api
  labels:
    app: user-service-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-rest-api
  template:
    metadata:
      labels:
        app: user-service-rest-api
    spec:
      containers:
      - name: user-service-rest-api
        image: sachinsharma1001/user-service-rest-api:latest
        imagePullPolicy: Always 
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15  
            periodSeconds: 20      
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRESS_USERNAME
            value: udagramsachindev
          - name: POSTGRESS_PASSWORD
            value: udagramsachindev
          - name: POSTGRESS_DATABASE
            value: udagramsachindev  
          - name: POSTGRESS_HOST
            value: udagram-microservices-dev.cp1awku8suyh.us-east-2.rds.amazonaws.com
          - name: POSTGRESS_DIALECT
            value: postgres 
          - name: AWS_REGION
            value: us-east-2
          - name: AWS_PROFILE
            value: default  
      restartPolicy: Always  