apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
  labels:
    run: user-service-rest-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: user-service-rest-api

